name: remaat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  expansion_widget: ^0.0.3
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  fluster: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launch: ^0.3.0
  flutter_local_notifications: ^9.9.0
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^1.0.4
  flutter_speed_dial: ^6.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.1
  geocoder2: ^1.4.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.12
  google_maps_flutter_web: ^0.4.0+2
  # haversine_distance: ^1.2.1
  dropdown_button2: ^1.0.0
  http: ^0.13.5
  intl: ^0.17.0
  location: ^4.4.0
  lottie: ^1.4.2
  maps_launcher: ^2.0.1
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  rating: ^1.0.0-dev.1
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  simple_animations: ^4.0.2
  slide_to_act: ^2.0.1
  supercharged: ^2.1.1
  timelines: ^0.1.0
  twilio_phone_verify: ^2.0.0
  unicons: ^2.1.0
  url_launcher: ^6.1.5
  tabbed_sliverlist: ^0.1.0
  flutter_foreground_task: ^3.10.0
  fl_location: ^1.2.2
  flutter_barcode_scanner: ^2.0.0
  flutter_octicons: ^0.14.0
  

  disable_battery_optimization: ^1.1.0+1
  workmanager: ^0.5.0
  background_location:
    git:
      url: https://github.com/Almoullim/background_location
      ref: v0.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/icons/
    - assets/process_timeline/
    - lib/i10n/en.json
    - lib/i10n/ar.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo_remaat.png"
  min_sdk_android: 2
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: quick
      fonts:
        - asset: assets/fonts/quick.ttf
    - family: quick_bold
      fonts:
        - asset: assets/fonts/quick_bold.ttf
    - family: quick_semi
      fonts:
        - asset: assets/fonts/quick_semi.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
