// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvwbe-ytIQgwtwTD0hyysw495goydWNwA',
    appId: '1:776334758918:web:d71d9cb824998a2cdc1f87',
    messagingSenderId: '776334758918',
    projectId: 'remaat-2ccd7',
    authDomain: 'remaat-2ccd7.firebaseapp.com',
    storageBucket: 'remaat-2ccd7.appspot.com',
    measurementId: 'G-FZDBMZ1BNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_Z5vNVEANji13YvCWoA5IWTfphKZjEg',
    appId: '1:776334758918:android:580fe93a2fb65598dc1f87',
    messagingSenderId: '776334758918',
    projectId: 'remaat-2ccd7',
    storageBucket: 'remaat-2ccd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJmy8w5ye6NA89T8CTraAVV-qZRAnOctM',
    appId: '1:776334758918:ios:ca8256ebcf3da5b5dc1f87',
    messagingSenderId: '776334758918',
    projectId: 'remaat-2ccd7',
    storageBucket: 'remaat-2ccd7.appspot.com',
    iosClientId: '776334758918-5t3tm8v2n8ldev5ig1msij80qjicvee5.apps.googleusercontent.com',
    iosBundleId: 'com.company.coldt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJmy8w5ye6NA89T8CTraAVV-qZRAnOctM',
    appId: '1:776334758918:ios:ca8256ebcf3da5b5dc1f87',
    messagingSenderId: '776334758918',
    projectId: 'remaat-2ccd7',
    storageBucket: 'remaat-2ccd7.appspot.com',
    iosClientId: '776334758918-5t3tm8v2n8ldev5ig1msij80qjicvee5.apps.googleusercontent.com',
    iosBundleId: 'com.company.coldt',
  );
}
